import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div
          className="min-h-screen w-screen bg-cover bg-center"
          style={{
            backgroundImage: "url('/background.png')",
            backgroundSize: "25%", // Adjusted to make the image smaller
            border: "none",
          }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
