spring:
  application:
    name: puzzle-websocket-server
  r2dbc:
      url: r2dbc:postgresql://localhost:5433/lamapuz
      username: lama
      password: secret
  pool:
    enabled: true  
  datasource:
    driver-class-name: org.postgresql.Driver  
  sql:
    init:
      platform: none 
logging:
  level:
    root: DEBUG




