spring:
  application:
    name: puzzle-websocket-server
  redis:
    host: localhost
    port: 6379
    r2dbc:
      url: r2dbc:postgresql://localhost:5432/puzzle_db
      username: postgres
      password: yourpassword

logging:
  level:
    root: DEBUG




