spring:
  application:
    name: puzzle-resource-server
  datasource:
    scheme: classpath:schema.sql
    data: classpath:data.sql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/lamapuz
    username: lama
    password: secret
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always


scheme: http
hostname: localhost
reverse-proxy-port: 7080
reverse-proxy-uri: ${scheme}://${hostname}:${reverse-proxy-port}
authorization-server-prefix: /auth
issuer: https://nguechngoac.io/auth/realms/lamapuz
username-claim-json-path: $.preferred_username
authorities-json-path: $.realm_access.roles
resource-server-port: 7084
audience: 

server:
  port: ${resource-server-port}
  ssl:
    enabled: false

com:
  c4-soft:
    springaddons:
      oidc:
        ops:
        - iss: ${issuer}
          username-claim: ${username-claim-json-path}
          authorities:
          - path: ${authorities-json-path}
          aud: ${audience}
        resourceserver:
          permit-all:
          - /me
          - /actuator/health/readiness
          - /actuator/health/liveness
          
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    root: DEBUG
    org:
      springframework:
        boot: DEBUG
        security: DEBUG
        web: DEBUG
        
---
spring:
  config:
    activate:
      on-profile: ssl
server:
  ssl:
    enabled: true
scheme: https
